// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Spgr_bhf3
Rcpp::List Spgr_bhf3(arma::vec indexy, arma::vec& y, arma::mat& x, arma::vec& weights, arma::mat& betam0, double nu, double gam, double lam, int maxiter, double tolabs, double tolrel);
RcppExport SEXP _SpgrBHF_Spgr_bhf3(SEXP indexySEXP, SEXP ySEXP, SEXP xSEXP, SEXP weightsSEXP, SEXP betam0SEXP, SEXP nuSEXP, SEXP gamSEXP, SEXP lamSEXP, SEXP maxiterSEXP, SEXP tolabsSEXP, SEXP tolrelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type indexy(indexySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type betam0(betam0SEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tolabs(tolabsSEXP);
    Rcpp::traits::input_parameter< double >::type tolrel(tolrelSEXP);
    rcpp_result_gen = Rcpp::wrap(Spgr_bhf3(indexy, y, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel));
    return rcpp_result_gen;
END_RCPP
}
// loglik3
arma::vec loglik3(arma::vec par, arma::vec indexy, arma::vec& y, arma::mat& x, arma::mat& betam, List matls, List diagls, arma::uvec nJ);
RcppExport SEXP _SpgrBHF_loglik3(SEXP parSEXP, SEXP indexySEXP, SEXP ySEXP, SEXP xSEXP, SEXP betamSEXP, SEXP matlsSEXP, SEXP diaglsSEXP, SEXP nJSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type indexy(indexySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type betam(betamSEXP);
    Rcpp::traits::input_parameter< List >::type matls(matlsSEXP);
    Rcpp::traits::input_parameter< List >::type diagls(diaglsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type nJ(nJSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik3(par, indexy, y, x, betam, matls, diagls, nJ));
    return rcpp_result_gen;
END_RCPP
}
// BIC_bhf3
double BIC_bhf3(Rcpp::List obj);
RcppExport SEXP _SpgrBHF_BIC_bhf3(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(BIC_bhf3(obj));
    return rcpp_result_gen;
END_RCPP
}
// BICc_bhf3
double BICc_bhf3(Rcpp::List obj, double c0);
RcppExport SEXP _SpgrBHF_BICc_bhf3(SEXP objSEXP, SEXP c0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    rcpp_result_gen = Rcpp::wrap(BICc_bhf3(obj, c0));
    return rcpp_result_gen;
END_RCPP
}
// scad
arma::vec scad(arma::vec v, double lam, double nu, double gam);
RcppExport SEXP _SpgrBHF_scad(SEXP vSEXP, SEXP lamSEXP, SEXP nuSEXP, SEXP gamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type gam(gamSEXP);
    rcpp_result_gen = Rcpp::wrap(scad(v, lam, nu, gam));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpgrBHF_Spgr_bhf3", (DL_FUNC) &_SpgrBHF_Spgr_bhf3, 11},
    {"_SpgrBHF_loglik3", (DL_FUNC) &_SpgrBHF_loglik3, 8},
    {"_SpgrBHF_BIC_bhf3", (DL_FUNC) &_SpgrBHF_BIC_bhf3, 1},
    {"_SpgrBHF_BICc_bhf3", (DL_FUNC) &_SpgrBHF_BICc_bhf3, 2},
    {"_SpgrBHF_scad", (DL_FUNC) &_SpgrBHF_scad, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpgrBHF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
