# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scad <- function(v, lam, nu, gam) {
    .Call(`_SpgrBHF_scad`, v, lam, nu, gam)
}

Spgr_bhf3 <- function(indexy, y, x, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 100L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call(`_SpgrBHF_Spgr_bhf3`, indexy, y, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

loglik3 <- function(par, indexy, y, x, betam, matls, diagls, nJ) {
    .Call(`_SpgrBHF_loglik3`, par, indexy, y, x, betam, matls, diagls, nJ)
}

BIC_bhf3 <- function(obj) {
    .Call(`_SpgrBHF_BIC_bhf3`, obj)
}

